name: guidemap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  beamer: ^1.6.1
  cloud_firestore: ^4.16.0
  firebase_core: ^2.28.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/icons/
