name: guidemap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.19.4
  firebase_core: ^2.28.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_launcher_icons: ^0.13.1
  geolocator: ^11.0.0
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: true
  ios: true